### ISSUE TITLE
filesize for upload big dump files

### ISSUE THREAD

**Issue by mratix** [hassio-addons/addon-phpmyadmin#10]
Is possible to add configuration options for the php.ini?
Per default ```upload_max_filesize = 2.048KiB``` was to low for dumps.

Documented in faq.html#faq1-16:

1.16 I cannot upload big dump files (memory, HTTP or timeout problems).
Starting with version 2.7.0, the import engine has been re–written and these problems should not occur. If possible, upgrade your phpMyAdmin to the latest version to take advantage of the new import features.

The first things to check (or ask your host provider to check) are the values of max_execution_time, upload_max_filesize, memory_limit and post_max_size in the php.ini configuration file. All of these settings limit the maximum size of data that can be submitted and handled by PHP. Please note that post_max_size needs to be larger than upload_max_filesize. There exist several workarounds if your upload is too big or your hosting provider is unwilling to change the settings:

    Look at the $cfg['UploadDir'] feature. This allows one to upload a file to the server via scp, FTP, or your favorite file transfer method. PhpMyAdmin is then able to import the files from the temporary directory. More information is available in the Configuration of this document.

    Using a utility (such as BigDump) to split the files before uploading. We cannot support this or any third party applications, but are aware of users having success with it.

    If you have shell (command line) access, use MySQL to import the files directly. You can do this by issuing the “source” command from within MySQL:

    source filename.sql;

**Comment by sinclairpaul** [comment]
What size limit do you need, as this is also limited by the supervisor, which I believe is ~128Mb

**Comment by frenck** [comment]
Right now, we have not a way to provide a solutions to your request.
we can up the size a bit, to max 16Mb, but more isn't allowed in Ingress.

The MySQL command-line tools are available on the Community SSH & Web Terminal add-on or the VSCode add-on. Those allow for larger import/exports/
