### ISSUE TITLE
Unable to import back-up files greater then 2.048KB

### ISSUE THREAD

**Issue by sldewit** [hassio-addons/addon-phpmyadmin#116]
# Problem/Motivation

I'm trying to import a back-up from my MariaDB on Synology NAS back on my Odroid N2+ Home assistant environment, but there is a limitation of 2.048KB on the import files. 

## Expected behavior

I would expect this to be a larger import file size or be able to change it somewhere.

## Actual behavior

See above
![image](https://user-images.githubusercontent.com/54032526/148341570-e5ac5d0e-ca02-4d84-9a94-91a44e38da25.png)

## Steps to reproduce

It actually says this limitation exists on the import tab itself, so it should be easy to find. Als can find a bunch of solutions on google, but I'm unable to apply them to this setup. 

## Proposed changes

Proposal is to fix this to a higher number so the actual Home Assistant database can be exported and imported without any issues. If there is another way to import the backup from another MariaDB that is also fine for me. 
The current database is about 900MB large. The export file is about 650 MB

**Comment by sldewit** [comment]
In the meantime I found another tool to get my data imported. So this can be closed for me.

**Comment by frenck** [comment]
Re-opening, as this needs to be solved

**Comment by sldewit** [comment]
Job we'll done @frenck !!!

**Comment by frenck** [comment]
Don't thank me, this was all @sinclairpaul who made this 😄
