### ISSUE TITLE
Error to execute

### ISSUE THREAD

**Issue by angeltonio** [hassio-addons/addon-phpmyadmin#12]
this  the log..

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.1.2
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: Ubuntu 19.10  (amd64 / qemux86-64)
 Home Assistant Core: 0.109.6
 Home Assistant Supervisor: 222
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] phpmyadmin.sh: executing... 
[19:35:34] ERROR: Got unexpected response from the API: Service not enabled
[cont-init.d] phpmyadmin.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by sinclairpaul** [comment]
Please make sure you have installed the MariaDB addon.
