### ISSUE TITLE
addon-phpmyadmin not found

### ISSUE THREAD

**Issue by javferper** [hassio-addons/addon-phpmyadmin#126]
Hello, I would like to install the
addon-phpmyadmin (https://github.com/hassio-addons/addon-phpmyadmin.git) The addon not found error automatically appears. Manually the error Invalid Add-on repository!
any solution? Thank you so much
Javier Fernández
Home Assistant OS 8.1
core-2022.5.5
supervisor-2022.05.3

![image](https://user-images.githubusercontent.com/94490352/169915914-810a2fe1-c769-465e-9f52-8cc66bc784b1.png)

**Comment by sinclairpaul** [comment]
Please look at the readme if the repo is missing <https://github.com/hassio-addons/addon-phpmyadmin/blob/main/phpmyadmin/DOCS.md#installation>

**Comment by javferper** [comment]
It's already working
Thank you very much
Greetings
