### ISSUE TITLE
Please increase File Size limit 64MB is way too small 

### ISSUE THREAD

**Issue by MasterCATZ** [hassio-addons/addon-phpmyadmin#127]
nginx is set for 4G why have you done a hard limit for 64MB ? 
you should have at least allowed the manual changed settings to stay 

every-time I need to export / Import (which seems to be every update these days or else migration fails )
I have to go back into the container and change everything to allow files to move around , its a shame every reset it reverts back

**Comment by sinclairpaul** [comment]
There is a config option, does this not work for you?
https://github.com/hassio-addons/addon-phpmyadmin/blob/main/phpmyadmin/DOCS.md#option-upload_limit

**Comment by sinclairpaul** [comment]
Closing as no response
