### ISSUE TITLE
Missing add-on under Home Assistant Core 2022.6.3 Home Assistant Supervisor 2022.05.3

### ISSUE THREAD

**Issue by flowersrj** [hassio-addons/addon-phpmyadmin#128]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Ensure that https://github.com/hassio-addons/repository is listed under the addon repos

**Comment by flowersrj** [comment]
Paul,

 

That did it.

 

Thanks,

Rich 

 

 

 

 
 

Sent: Monday, June 06, 2022 at 8:08 PM
