### ISSUE TITLE
Add-on will not start

### ISSUE THREAD

**Issue by jj-uk** [hassio-addons/addon-phpmyadmin#137]
# Problem/Motivation
After installing he add-on and starting, the add-on doesn't start (red icon).

## Expected behavior
The add-on should start and the icon turn green.

## Actual behavior
The logs show that the add-on is started, but the add-on page shows the add-on is not started.

## Steps to reproduce
Install the add-on.
Start the add-on.

## Proposed changes

Add-on Logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.9.7
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/phpmyadmin.sh
cont-init: info: /etc/cont-init.d/phpmyadmin.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
[13:00:14] INFO: Starting PHP-FPM...
[13:00:14] INFO: Starting NGinx....
```

**Comment by krism23** [comment]
Same for me:
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (amd64 / qemux86-64)
 Home Assistant Core: 2022.10.2
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/phpmyadmin.sh
[07:36:20] ERROR: Got unexpected response from the API: Service not enabled
cont-init: info: /etc/cont-init.d/phpmyadmin.sh exited 139
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by frenck** [comment]
@jj-uk In your logs, the add-on seems to be running. I think you might have been running into a Supervisor issue. Try rebooting your system, and see if the status resolves/picks up on startup.

**Comment by frenck** [comment]
@krism23 Your add-on doesn't start, as it didn't get credentials for accessing the MariaDB add-on. Indicated by this in the logs:

> [07:36:20] ERROR: Got unexpected response from the API: Service not enabled

Please be sure to install the MariaDB add-on and make sure it is started.

**Comment by jj-uk** [comment]
> @jj-uk In your logs, the add-on seems to be running. I think you might have been running into a Supervisor issue. Try rebooting your system, and see if the status resolves/picks up on start-up.

Restarting the host fixed it for me.
