### ISSUE TITLE
Is it possible to increase the timeout from client to server when running longer SQL queries?

### ISSUE THREAD

**Issue by dmshimself** [hassio-addons/addon-phpmyadmin#142]
# Problem/Motivation
Quite often when I run a long-ish SQL query on my older HA server box, I get an error:
![Screenshot_2022-11-10_11-45-10](https://user-images.githubusercontent.com/6901481/200958928-cb198e2c-2185-4099-9bab-786bffaa4dd8.png)

I know that the query often runs for 5 mins or so and I'm happy with that as I know my machine is a bit on the slow side.  But ideally I'd like to be able to up whatever the timeout value is.

## Expected behavior

I'd like to get the results of the query without a timeout and I'm happy to just leave things to run for ages if necessary to do this.

## Actual behavior

Most times I get the error in the screenshot shown above, sometimes I get results back.

## Steps to reproduce

In my case I run a query which lists the top N size of entity states used and if there are a lot, then it will generally timeout.  If I truncate the DB so that only 1-2 days of data is retained, it will work just fine.  My retention is 10 days.  A typical query is:

`select
  entity_id
, b.cnt
, round(b.cnt * 100 / (select count(*) from states), 2) as "cnt_pct"
, b.bytes
, round(b.bytes * 100 / (select sum(length(shared_attrs)) from state_attributes), 2) as "bytes_pct"
from (
  select entity_id, count(*) as "cnt", sum(length(shared_attrs)) as "bytes"
  from ( select distinct s.entity_id, sa.attributes_id, sa.shared_attrs
         from states s join state_attributes sa on sa.attributes_id = s.attributes_id
       ) a
  group by entity_id
) b
order by bytes desc;`

## Proposed changes

Ideally I'd like to have a parameter in the configuration section to let me adjust the timeout

**Comment by bakerkj** [comment]
@dmshimself have you found a work around for this issue?

**Comment by dmshimself** [comment]
a work around?  Yes, I switched to use a mariadb container.  That ran much more quickly and didn't get this issue.  I used the scripts from 

https://tteck.github.io/Proxmox/

as I use proxmox, but I'm sure there will be other rigs for running mariadb separately.

**Comment by bakerkj** [comment]
@dmshimself thanks!

**Comment by Tom-Heitbrink** [comment]
any way to solve it when using mariadb addon and phpadmin addon ?

**Comment by frenck** [comment]
Added in #142
