### ISSUE TITLE
No Run

### ISSUE THREAD

**Issue by superino1** [hassio-addons/addon-phpmyadmin#143]
# Problem
Hi, I have update to the latest version of ha, the component no longer starts

**Comment by frenck** [comment]
Please provide reproduction details, things like logs, and other things that could provide me details in helping you.

> the component no longer starts

That is not something I can help you with. "It doesn't work" doesn't provide details to be able to provide help.

**Comment by superino1** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.8.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.12.3
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/phpmyadmin.sh
cont-init: info: /etc/cont-init.d/phpmyadmin.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:23:31] INFO: Starting PHP-FPM...
[10:23:32] INFO: Starting NGinx....

**Comment by superino1** [comment]
Stop here

**Comment by frenck** [comment]
That log looks great, the add-on is running fine.

What is not working or what other behavior do you see?

../Frenck

**Comment by superino1** [comment]
![IMG_20221212_102837](https://user-images.githubusercontent.com/74857272/207010252-b02d4ccb-5e3f-4a46-bf94-329e0caca317.jpg)
It always stays that way

**Comment by superino1** [comment]
I've tried several times.  Thanks anyway for your effort

**Comment by frenck** [comment]
> I've tried several times.

Tried what several times? 🤷 

> Thanks anyway for your effort

So it is solved? Or not? I'm confused.

**Comment by superino1** [comment]
I have not solved.  I have tried several times to restart.

**Comment by frenck** [comment]
Not restart... Reboot your whole system.

Restart & reboot are not the same things...

**Comment by superino1** [comment]
I did all the tests, the problem is that Mariadb doesn't even start anymore

**Comment by frenck** [comment]
> the problem is that Mariadb doesn't even start anymore

That I cannot help you with, that is not related to this add-on. However, this add-on will not function without a running MariaDB.
