### ISSUE TITLE
[Feature] Add phpLiteAdmin

### ISSUE THREAD

**Issue by mdeweerd** [hassio-addons/addon-phpmyadmin#147]
# Problem/Motivation

Rather than adding another add-on and duplicating resources (php), it seems like a good idea to add phpLiteAdmin to this addon.

## Expected behavior

Access HA, ZHA sqlite3 databases through the phpLiteAdmin interface.

### phpLiteAdmin
- https://www.phpliteadmin.org/demo/
- https://www.phpliteadmin.org/download/
- https://bitbucket.org/phpliteadmin/public/src/master/

### Docker "examples"
- https://hub.docker.com/r/vtacquet/phpliteadmin

However, it does not seem to be compatible with php8, the main page mentions php7.3.9 .

**Comment by tjorim** [comment]
No updates since 2021 and there already is an add-on for SQLite anyway: https://github.com/hassio-addons/addon-sqlite-web.

**Comment by mdeweerd** [comment]
The sqlite web addon does not allow easy updates (need to write SQL), phpliteadmin is easier.

**Comment by tjorim** [comment]
I'll leave it up to Frenck but nonetheless it's not an issue or bug and should not be opened here.
