### ISSUE TITLE
Phpmyadmin not starting on RPI HA

### ISSUE THREAD

**Issue by lukaszs1942** [hassio-addons/addon-phpmyadmin#165]
# Problem/Motivation

Unable to start phpmyadmin on System: Home Assistant OS 10.1 (aarch64 / raspberrypi3-64)

## Expected behavior

phpmyadmin started sucesfully.

## Actual behavior

Bad gateway " 502: Bad Gateway"  on frontend and error in logs: s6-rc: warning: unable to start service init-phpmyadmin: command exited 128

## Steps to reproduce

Try to start phpmyadmin on RPI 3b

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Logs:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.8.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.5.3
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-phpmyadmin: starting
s6-rc: info: service init-nginx: starting
[13:01:57] DEBUG: Requested API resource: http://supervisor/services/mysql
[13:01:57] DEBUG: Request method: GET
[13:01:57] DEBUG: Request data: {}
[13:01:57] DEBUG: API HTTP Response code: 400
[13:01:57] DEBUG: API Response: {"result": "error", "message": "Service not enabled"}
s6-rc: info: service init-nginx successfully started
[13:01:58] ERROR: Got unexpected response from the API: Service not enabled
s6-rc: warning: unable to start service init-phpmyadmin: command exited 128
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-nginx: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by frenck** [comment]
```
[13:01:58] ERROR: Got unexpected response from the API: Service not enabled
```

The MariaDB add-on this add-on manages is not there, therefore, the add-on cannot start/provide anything useful.

../Frenck
