### ISSUE TITLE
Addon not starting

### ISSUE THREAD

**Issue by Med-WAHIB** [hassio-addons/addon-phpmyadmin#18]
# Problem/Motivation

> Problem when starting the addon

## Expected behavior

> The addon to start normally

## Actual behavior

> Addon not starting

## Steps to reproduce

> I installed the addon (after installing and starting the MariaDB addon), when it starts Iget this log, then it stops.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
curl: (28) Failed to connect to supervisor port 80: Operation timed out
[16:02:41] ERROR: Something went wrong contacting the API
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] phpmyadmin.sh: executing... 
curl: (28) Failed to connect to supervisor port 80: Operation timed out
[16:04:54] ERROR: Something went wrong contacting the API
[cont-init.d] phpmyadmin.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
                Oops! Something went wrong.
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 Be sure to check the log above, line by line, for hints.
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

## Proposed changes

> none, please help

**Comment by frenck** [comment]
Please provide your system details. e.g., by running the `ha info` in your terminal.

**Comment by sernunez** [comment]
`arch: armv7
channel: stable
docker: 20.10.2
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.1.4
hostname: raspberrypi
logging: info
machine: raspberrypi4
operating_system: Raspbian GNU/Linux 10 (buster)
supervisor: 2021.01.4
supported: false
supported_arch:
- armv7
- armhf
timezone: America/Montevideo`

**Comment by frenck** [comment]
🤷  Sorry not sure, but `Raspbian GNU/Linux 10 (buster)` is not a supported system by the Home Assistant project.

Meaning this is not a problem that concerns this project either.

**Comment by Med-WAHIB** [comment]
@frenck sorry for being a bit late...

> Please provide your system details. e.g., by running the `ha info` in your terminal.

My ha info is : 
arch: armv7
channel: stable
docker: 19.03.13
features:
- reboot
- shutdown
- services
- network
- hostname
- hassos
hassos: "5.9"
homeassistant: 2021.1.4
hostname: homeassistant
logging: info
machine: raspberrypi4
operating_system: Home Assistant OS 5.9
supervisor: 2021.01.4
supported: true
supported_arch:
- armv7
- armhf
timezone: Africa/Casablanca
