### ISSUE TITLE
service user and password?

### ISSUE THREAD

**Issue by Rothammel** [hassio-addons/addon-phpmyadmin#188]
Hy phpmyadmin exit with bad gateway and in the MariaDB addon I have this error:

`2023-10-16 18:40:43 24 [Warning] Access denied for user 'service'@'172.30.33.13' (using password: YES`

what is the password for the service user? maybe this user doesn't exist anymore?

**Comment by frenck** [comment]
That is a good question. This add-on gets this information provided by the Supervisor. The Supervisor gets this data pushed by the Maria DB add-on. 

This is not something this add-on can do anything about. It just connects with the data provided.

../Frenck
