### ISSUE TITLE
ERROR: Got unexpected response from the API: Service not enabled

### ISSUE THREAD

**Issue by vpomax** [hassio-addons/addon-phpmyadmin#3]
Hassio 0.105.2
I just installed it and have this error on start:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: Resin OS 2.3.0+rev1  (armv7 / raspberrypi3)
 Home Assistant Core: 0.105.2
 Home Assistant Supervisor: 200
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] phpmyadmin.sh: executing... 
[00:13:56] ERROR: Got unexpected response from the API: Service not enabled
[cont-init.d] phpmyadmin.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by sinclairpaul** [comment]
Do you have the MariaDB addon installed and running?

**Comment by naamah75** [comment]
Same for me ...

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: phpMyAdmin
 A web interface for the official MariaDB add-on
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.105.4
 Home Assistant Supervisor: 200
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] phpmyadmin.sh: executing... 
[06:25:47] ERROR: Got unexpected response from the API: Service not enabled
[cont-init.d] phpmyadmin.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by naamah75** [comment]
> Do you have the MariaDB addon installed and running?

Obviously!

**Comment by naamah75** [comment]
Solved in a very easy way! Just updated MaridDB add-on to 2.0.
Sorry for that!

**Comment by vpomax** [comment]
Yes I have it and it is running... this is MariaDB log:

Log
[11:23:07] INFO: Using existing mariadb initial system
[11:23:07] INFO: Starting MariaDB
200216 11:23:07 mysqld_safe Logging to '/data/databases/core-mariadb.local.hass.io.err'.
200216 11:23:07 mysqld_safe Starting mysqld daemon with databases from /data/databases
[11:23:10] INFO: Check data integrity and fix corruptions
[11:23:11] INFO: Init custom database
[11:23:11] INFO: Create database homeassistant
[11:23:11] INFO: Init/Update users
[11:23:16] INFO: Update user hass
[11:23:16] INFO: Init/Update rights
[11:23:18] INFO: Alter rights for hass@% - homeassistant

**Comment by frenck** [comment]
The add-on needs at least version 2.0 or higher of the MariaDB (as documented in the add-on documentation).

**Comment by vpomax** [comment]
Ok, after I upgraded MariaDB to 2.0 it works.
