### ISSUE TITLE
TempDir not approachable

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/addon-phpmyadmin#6]
# Problem/Motivation

phpMyAdmin seems to work fine but gives an error message at the bottom:

`De $cfg['TempDir'] (/var/www/phpmyadmin/tmp/) is niet benaderbaar. phpMyAdmin kan de templates niet in de cache zetten en zal daardoor langzamer werken.`

## Expected behavior

No error messages are provided.

## Actual behavior

Users get an error message.

## Steps to reproduce

Just clean install and open the webui.

## Proposed changes

Either create the default dir `/var/www/phpmyadmin/tmp/` (change [this line](https://github.com/hassio-addons/addon-phpmyadmin/blob/master/phpmyadmin/Dockerfile#L24) to `mkdir -p /var/www/phpmyadmin/tmp \`?) or set the TempDir in config to another location (in [this file](https://github.com/hassio-addons/addon-phpmyadmin/blob/master/phpmyadmin/rootfs/etc/phpmyadmin/config.inc.php) should work?), not sure what's the preferred solution.

**Comment by frenck** [comment]
I'll look into this, I guess making use the system's provided temporary directory makes more sense, or maybe even make a in-memory one.

**Comment by frenck** [comment]
Fixed on dev
